In [1]:
%matplotlib inline


A simple linear regression
===========================

https://scipy-lectures.org/packages/scikit-learn/auto_examples/plot_linear_regression.html#sphx-glr-download-packages-scikit-learn-auto-examples-plot-linear-regression-py


In [2]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression



In [3]:
model = LinearRegression()
print(model)

LinearRegression()


In [4]:
x = np.array([0,1,2,3,4,5])
y = np.array([2, 3, 4,5,6,7])

print(x)
plt.plot(x, y, marker='o')

[0 1 2 3 4 5]


In [5]:
X = x[:, np.newaxis] # The input data for sklearn is 2D: (samples == 6 x features == 1)



print(X)




[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]


In [6]:

lr = model.fit(X, y)

print(lr.predict([[10]]))

#faire apprentissage

#aX+b=y

print('lr.coef (a): {}'.format(lr.coef_))
print('lr.intercept (b): {}'.format(lr.intercept_))

print(lr.coef_*10 +lr.intercept_)

[12.]
lr.coef (a): [1.]
lr.intercept (b): 2.0
[12.]


In [7]:
# Create some simple data
import numpy as np
np.random.seed(0)
X = np.random.random(size=(10, 1))

print(X)




[[0.5488135 ]
 [0.71518937]
 [0.60276338]
 [0.54488318]
 [0.4236548 ]
 [0.64589411]
 [0.43758721]
 [0.891773  ]
 [0.96366276]
 [0.38344152]]


In [8]:
print(" x \n {} \n ".format(X[:,0]))

#Etiquette
y = 5 * X[:, 0] + 3 + np.random.normal(size=10) #on ajoute du bruit aléatoire 

print("y \n{} \n".format(y))


 x 
 [0.5488135  0.71518937 0.60276338 0.54488318 0.4236548  0.64589411
 0.43758721 0.891773   0.96366276 0.38344152] 
 
y 
[5.88811109 8.03022034 6.77485461 5.84609093 5.56213723 6.56314489
 6.68201513 7.25370674 8.1313815  4.06311185] 



In [9]:
model = LinearRegression()
lr = model.fit(X, y)

print(' \n lr.coef (a): {}'.format(lr.coef_))
print('\n lr.intercept (b): {}'.format(lr.intercept_))

 
 lr.coef (a): [5.07554748]

 lr.intercept (b): 3.3541264255241425


In [10]:

plt.scatter(X[:, 0], y, label='donnee')

yr = np.array(lr.coef_ * X[:, 0] + lr.intercept_)

plt.plot(X[:, 0], yr, '-', c='red', label='lr')
plt.legend()

In [11]:

model.score(X,y)

0.6591805506414798

In [12]:
model.predict([[1]])




array([8.4296739])

In [13]:
# predict y from the data
Xe = np.linspace(0, 6, 10)
Xe = Xe[:, np.newaxis]
ye = model.predict(Xe)


print(" x \n {} \n ".format(Xe[:,0]))



print("y \n{} \n".format(ye))


plt.scatter(Xe[:, 0], ye, label='estimation')

yr = np.array(lr.coef_ * Xe[:, 0] + lr.intercept_)

plt.plot(Xe[:, 0], yr, '-', c='red', label='lr')
plt.legend()


 x 
 [0.         0.66666667 1.33333333 2.         2.66666667 3.33333333
 4.         4.66666667 5.33333333 6.        ] 
 
y 
[ 3.35412643  6.73782474 10.12152306 13.50522138 16.8889197  20.27261802
 23.65631634 27.04001466 30.42371297 33.80741129] 



**Si on augmente la taille de data set**

Refaire le même exemple avec la taille de données 100

In [14]:
# Create some simple data
import numpy as np
np.random.seed(0)
X2 = np.random.random(size=(100, 1))
y2 = 5 * X2[:, 0] + 3 + np.random.normal(size= 100) #on ajoute du bruit aléatoire 


print(" x \n {} \n ".format(X2[:,0]))

print("y \n {} \n ".format(y2))

 x 
 [0.5488135  0.71518937 0.60276338 0.54488318 0.4236548  0.64589411
 0.43758721 0.891773   0.96366276 0.38344152 0.79172504 0.52889492
 0.56804456 0.92559664 0.07103606 0.0871293  0.0202184  0.83261985
 0.77815675 0.87001215 0.97861834 0.79915856 0.46147936 0.78052918
 0.11827443 0.63992102 0.14335329 0.94466892 0.52184832 0.41466194
 0.26455561 0.77423369 0.45615033 0.56843395 0.0187898  0.6176355
 0.61209572 0.616934   0.94374808 0.6818203  0.3595079  0.43703195
 0.6976312  0.06022547 0.66676672 0.67063787 0.21038256 0.1289263
 0.31542835 0.36371077 0.57019677 0.43860151 0.98837384 0.10204481
 0.20887676 0.16130952 0.65310833 0.2532916  0.46631077 0.24442559
 0.15896958 0.11037514 0.65632959 0.13818295 0.19658236 0.36872517
 0.82099323 0.09710128 0.83794491 0.09609841 0.97645947 0.4686512
 0.97676109 0.60484552 0.73926358 0.03918779 0.28280696 0.12019656
 0.2961402  0.11872772 0.31798318 0.41426299 0.0641475  0.69247212
 0.56660145 0.26538949 0.52324805 0.09394051 0.5759465  0.92

In [15]:
model2 = LinearRegression()
lr2 = model2.fit(X2, y2)

print(' \n lr.coef (a): {}'.format(lr2.coef_))
print('\n lr.intercept (b): {}'.format(lr2.intercept_))

plt.scatter(X2[:, 0], y2, label='donnee')

yr2 = np.array(lr2.coef_ * X2[:, 0] + lr2.intercept_)

plt.plot(X2[:, 0], yr2, '-',c='red', label= 'lr')
plt.legend()

 
 lr.coef (a): [4.93693502]

 lr.intercept (b): 3.222151077447229


In [16]:
model.score(X2,y2)

0.6577387110220576

**Si on change le modèle**

Régression rigide  (régularisation)  

On impose des contraintes supplémentaires sur les paramètres de régression. Le but de 

https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.Ridge.html

In [17]:



from sklearn.linear_model import Ridge

model = Ridge(alpha=1)



lr3 = model.fit(X2,y2)

print(' \n lr.coef (a): {}'.format(lr3.coef_))
print('\n lr.intercept (b): {}'.format(lr3.intercept_))

plt.scatter(X2[:, 0], y2,label='donnees')

yr3 = np.array(lr3.coef_ * X2[:, 0] + lr3.intercept_)

plt.plot(X2[:, 0], yr3, '-', c='red', label='lr')
plt.legend()

 
 lr.coef (a): [4.40675344]

 lr.intercept (b): 3.47281766072159


In [18]:
model.score(X2,y2)


0.6634517236237736

In [19]:
model.predict([[1]]) #Prediction

array([7.87957111])